### ISSUE TITLE
Nodes configuration seems not working: Invalid HTTP host at org.apache.http.HttpHost.create(HttpHost.java:122) 

### ISSUE THREAD

**Issue by skler** [Norconex/committer-elasticsearch#21]
This is my config.xml crawler section:

```
<crawler id="testsite.com">
	<startURLs>
		<url>http://www.testsite.com</url>
	</startURLs>
	<committer class="${committer}.elasticsearch.ElasticsearchCommitter">
		<nodes>http://elasticsearch:9200/</nodes>
	</committer>
</crawler>
```

But running the crawler it crash at:
```java.lang.IllegalArgumentException: Invalid HTTP host: elasticsearch:9200/```

Here the full log:

```
norconex         | ERROR [AbstractBatchCommitter] Could not commit batched operations.
norconex         | java.lang.IllegalArgumentException: Invalid HTTP host: elasticsearch:9200/
norconex         | 	at org.apache.http.HttpHost.create(HttpHost.java:122)
norconex         | 	at com.norconex.committer.elasticsearch.ElasticsearchCommitter.createRestClient(ElasticsearchCommitter.java:594)
norconex         | 	at com.norconex.committer.elasticsearch.ElasticsearchCommitter.nullSafeRestClient(ElasticsearchCommitter.java:582)
norconex         | 	at com.norconex.committer.elasticsearch.ElasticsearchCommitter.commitBatch(ElasticsearchCommitter.java:418)
norconex         | 	at com.norconex.committer.core.AbstractBatchCommitter.commitAndCleanBatch(AbstractBatchCommitter.java:179)
norconex         | 	at com.norconex.committer.core.AbstractBatchCommitter.commitComplete(AbstractBatchCommitter.java:159)
norconex         | 	at com.norconex.committer.core.AbstractFileQueueCommitter.commit(AbstractFileQueueCommitter.java:233)
norconex         | 	at com.norconex.committer.elasticsearch.ElasticsearchCommitter.commit(ElasticsearchCommitter.java:387)
norconex         | 	at com.norconex.collector.core.crawler.AbstractCrawler.execute(AbstractCrawler.java:270)
norconex         | 	at com.norconex.collector.core.crawler.AbstractCrawler.doExecute(AbstractCrawler.java:226)
norconex         | 	at com.norconex.collector.core.crawler.AbstractCrawler.startExecution(AbstractCrawler.java:189)
norconex         | 	at com.norconex.jef4.job.AbstractResumableJob.execute(AbstractResumableJob.java:49)
norconex         | 	at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:355)
norconex         | 	at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:296)
norconex         | 	at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:168)
norconex         | 	at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:132)
norconex         | 	at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:95)
norconex         | 	at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)
```

**Comment by essiembre** [comment]
Is Elasticsearch a custom hostname you created?  Try to reach it on port 9200 using telnet or else.  I suspect it is unreachable.

Another approach is to try with the IP instead.   Also, try without the trailing forward slash (I don't think it matters... but just to try).

Are you running it on the same server as Elasticsearch?  If so, you can also try with "http://localhost:9200".

**Comment by skler** [comment]
Ops, sorry. I didn't got your answer! 

I should double check, btw I can exclude the domain error, I guess is more related to an  error on code, I'll check later today!

**Comment by essiembre** [comment]
Closing due to lack of feedback.  If you still have the issue and you suspect a problem with the Committer, feel free to re-open.
