### ISSUE TITLE
Error when indexing to Elasticsearch through http collector

### ISSUE THREAD

**Issue by estauthamer** [Norconex/committer-elasticsearch#7]
Command:
`collector-http.bat -a start -c examples/kbenp-web-elastic/kbenp-web-elastic-config.xml` 
[kbenp-web-elastic-config.xml.txt](https://github.com/Norconex/committer-elasticsearch/files/649214/kbenp-web-elastic-config.xml.txt)

Error:
```
FATAL [JobSuite] Job suite execution failed: KBenP web elastic
java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
        at org.elasticsearch.threadpool.ThreadPool.<clinit>(ThreadPool.java:190)
        at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:131)
        at com.norconex.committer.elasticsearch.DefaultClientFactory.buildTransportClient(DefaultClientFactory.java:88)
        at com.norconex.committer.elasticsearch.DefaultClientFactory.createClient(DefaultClientFactory.java:54)
        at com.norconex.committer.elasticsearch.ElasticsearchCommitter.commitBatch(ElasticsearchCommitter.java:241)
        at com.norconex.committer.core.AbstractBatchCommitter.commitAndCleanBatch(AbstractBatchCommitter.java:179)
        at com.norconex.committer.core.AbstractBatchCommitter.commitComplete(AbstractBatchCommitter.java:159)
        at com.norconex.committer.core.AbstractFileQueueCommitter.commit(AbstractFileQueueCommitter.java:233)
        at com.norconex.collector.core.crawler.AbstractCrawler.execute(AbstractCrawler.java:255)
        at com.norconex.collector.core.crawler.AbstractCrawler.doExecute(AbstractCrawler.java:216)
        at com.norconex.collector.core.crawler.AbstractCrawler.startExecution(AbstractCrawler.java:179)
        at com.norconex.jef4.job.AbstractResumableJob.execute(AbstractResumableJob.java:49)
        at com.norconex.jef4.suite.JobSuite.runJob(JobSuite.java:350)
        at com.norconex.jef4.suite.JobSuite.doExecute(JobSuite.java:300)
        at com.norconex.jef4.suite.JobSuite.execute(JobSuite.java:172)
        at com.norconex.collector.core.AbstractCollector.start(AbstractCollector.java:120)
        at com.norconex.collector.core.AbstractCollectorLauncher.launch(AbstractCollectorLauncher.java:80)
        at com.norconex.collector.http.HttpCollector.main(HttpCollector.java:75)
```

**Comment by essiembre** [comment]
The method it complains of not finding is in the library ``guava-18.0.jar``.  For some reason, do you have another version of that file in your lib folder?

**Comment by estauthamer** [comment]
The file was there. I extracted it again from the elastic committer ZIP and now it works. The file was probably corrupt.

**Comment by essiembre** [comment]
Glad to hear. Thanks for confirming.
